export { default as HomeScreen } from './HomeScreen'
export { default as RoomsScreen } from './RoomsScreen'
export { default as RoomDetailScreen } from './RoomDetailScreen'
export { default as PatientDetailScreen } from './PatientDetailScreen'
export { default as HospitalScreen } from './HospitalScreen'
export { default as PatientsScreen } from './PatientsScreen'
export { default as DoctorsScreen } from './DoctorsScreen'